import {
  FileText,
  User,
  Briefcase,
  HardDrive,
  Search,
  AlertTriangle,
  Database,
  Lightbulb,
  Target,
  Settings,
  Clock,
  Percent,
  DollarSign,
  ShieldAlert,
  Info,
  CheckCircle,
  Wrench,
  Package,
  Shield,
  Link,
  Scale,
  Award,
  AlertCircle,
  XCircle,
  ClipboardCheck,
  FileWarning,
  ThumbsUp,
  type LucideIcon,
} from 'lucide-react';

const iconMap: Record<string, LucideIcon> = {
  'file-text': FileText,
  'user': User,
  'briefcase': Briefcase,
  'hard-drive': HardDrive,
  'search': Search,
  'alert-triangle': AlertTriangle,
  'database': Database,
  'lightbulb': Lightbulb,
  'target': Target,
  'settings': Settings,
  'clock': Clock,
  'percent': Percent,
  'dollar-sign': DollarSign,
  'shield-alert': ShieldAlert,
  'info': Info,
  'check-circle': CheckCircle,
  'wrench': Wrench,
  'package': Package,
  'shield': Shield,
  'link': Link,
  'scale': Scale,
  'award': Award,
  'alert-circle': AlertCircle,
  'x-circle': XCircle,
  'clipboard-check': ClipboardCheck,
  'file-warning': FileWarning,
  'thumbs-up': ThumbsUp,
};

export function getIconComponent(iconName?: string): LucideIcon {
  if (!iconName) return FileText;

  const icon = iconMap[iconName.toLowerCase()];
  return icon || FileText;
}
